CREATE TABLE IF NOT EXISTS records(
	id INT UNSIGNED AUTO_INCREMENT,
	department VARCHAR(200) NOT NULL,
	name VARCHAR(40) NOT NULL,
	reason VARCHAR(200) NOT NULL,
	duration FLOAT NOT NULL,
	date DATE NOT NULL,
	place VARCHAR(200) NOT NULL,
	open_id VARCHAR(100),
	submit_time DATETIME,
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;